website/auth.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from .models import User, AuditLog
from werkzeug.security import generate_password_hash, check_password_hash
from . import db, action
from flask_login import login_user, login_required, logout_user, current_user


auth = Blueprint('auth', __name__)

def log_event(user_id, action):
    entry = AuditLog(user_id=user_id, action=action)
    db.session.add(entry)
    db.session.commit()


@auth.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        email = request.form.get('email')
        password1 = request.form.get('password')

        user = User.query.filter_by(email=email).first()
        if user:
            if check_password_hash(user.password, password1):
                flash('Logged in successfully!', category='success')
                login_user(user, remember=True)
                log_event(user.id, action[0])
                return redirect(url_for('views.home'))
            else:
                flash('Incorrect password, try again.', category='error')
                log_event(user.id, action[1])
        else:
            flash('Email does not exist.', category='error')
            log_event(None, action[1])

    return render_template("login.html", user=current_user)


@auth.route('/logout')
@login_required
def logout():
    log_event(current_user.id, action[4])
    logout_user()
    return redirect(url_for('auth.login'))


@auth.route('/sign-up', methods=['GET', 'POST'])
def sign_up():
    if request.method == 'POST':
        email = request.form.get('email')
        first_name = request.form.get('firstName')
        password1 = request.form.get('password1')
        password2 = request.form.get('password2')
        is_admin = True if request.form.get('isAdmin') == '1' else False

        user = User.query.filter_by(email=email).first()
        if user:
            flash('Email already exists.', category='error')
            log_event(None, action[3])
        elif len(email) < 4:
            flash('Email must be greater than 3 characters.', category='error')
            log_event(None, action[3])
        elif len(first_name) < 2:
            flash('First name must be greater than 1 character.', category='error')
            log_event(None, action[3])
        elif password1 != password2:
            flash('Passwords don\'t match.', category='error')
            log_event(None, action[3])
        elif len(password1) < 7:
            flash('Password must be at least 7 characters.', category='error')
            log_event(None, action[3])
        else:
            new_user = User(email=email, first_name=first_name, password=generate_password_hash(
                password1, method='pbkdf2', salt_length=16), is_admin=is_admin)
            db.session.add(new_user)
            db.session.commit()
            login_user(new_user, remember=True)
            user = User.query.filter_by(email=email).first()
            log_event(user.id, action[2])
            flash('Account created!', category='success')
            return redirect(url_for('views.home'))

    return render_template("sign_up.html", user=current_user)

website/views.py
from flask import Blueprint, render_template, request, flash, jsonify, redirect, url_for
from flask_login import login_required, current_user
from .models import Note, AuditLog, User, create_admin
from . import db, action
import json

views = Blueprint('views', __name__)

@views.route('/admin/users', methods=['GET'])
@login_required
def admin_users(): # Ruta para mostrar usuarios (solo para administradores)
    if current_user.is_admin:  # Verifica si el usuario es administrador
        page = request.args.get('page', 1, type=int)
        per_page = 5
        users = User.query.paginate(page=page, per_page=per_page)  # Obtiene todos los usuarios
        return render_template("admin_users.html", users=users, current_user=current_user, user=current_user)  # Renderiza una plantilla para mostrar usuarios
    else:
        flash('Access denied. Only administrators can view users.', category='error')
        return redirect(url_for('views.home'))
    
@views.route('/admin/users/delete/<int:user_id>', methods=['POST'])
@login_required
def admin_delete_user(user_id): # Ruta para eliminar usuarios (solo para administradores)
    if current_user.is_admin:  # Verifica si el usuario es administrador
        user = User.query.get(user_id)  # Obtiene el usuario por su ID
        if user:
            db.session.delete(user)
            db.session.commit()
            log_admin_event(current_user.id, f"User {user.email} deleted by admin")
            flash('User deleted successfully.', category='success')
        else:
            flash('User not found.', category='error')
    else:
        flash('Access denied. Only administrators can delete users.', category='error')
    return redirect(url_for('views.admin_users'))

def log_admin_event(user_id, action): # Función para registrar eventos en AuditLog
    entry = AuditLog(user_id=user_id, action=action)
    db.session.add(entry)
    db.session.commit()

@views.route('/', methods=['GET', 'POST'])
@login_required
def home():
    if request.method == 'POST': 
        note = request.form.get('note')

        if len(note) < 1:
            flash('Note is too short!', category='error') 
        else:
            new_note = Note(data=note, user_id=current_user.id)
            db.session.add(new_note)
            db.session.commit()
            current_user.notes.append(new_note) 
            log_admin_event(current_user.id, action[5]) # Registro de evento - Agregar nota por un admin
            flash('Note added!', category='success')
    page = request.args.get('page', 1, type=int)
    per_page = 5
    user_notes = Note.query.filter_by(user_id=current_user.id).paginate(page=page, per_page=per_page)
    return render_template("home.html", user=current_user, user_notes=user_notes)

@views.route('/delete-note/<int:note_id>', methods=['GET'])
@login_required
def delete_note(note_id):
    note = Note.query.get(note_id)
    if not note:
        flash('Note not found!', category='error')
        return redirect(url_for('views.home'))
    
    if note.user_id != current_user.id:
        flash('Access denied. You are not authorized to delete this note.', category='error')
        return redirect(url_for('views.home'))
    
    db.session.delete(note)
    db.session.commit()
    flash('Note deleted successfully!', category='success')
    return redirect(url_for('views.home'))


@views.route('/edit-note/<int:note_id>', methods=['GET', 'POST'])
@login_required
def edit_note(note_id):
    note = Note.query.get(note_id)
    if not note:
        flash('Note not found!', category='error')
        return redirect(url_for('views.home'))

    if request.method == 'POST':
        new_data = request.form.get('new_data')
        if len(new_data) < 1:
            flash('Note is too short!', category='error')
        else:
            note.data = new_data
            db.session.commit()
            flash('Note updated!', category='success')
            return redirect(url_for('views.home'))

    return render_template("edit_note.html", note=note, user=current_user)

@views.route('/profile/<int:user_id>', methods=['GET'])
@login_required
def user_profile(user_id):
    profile_user = User.query.get(user_id)
    if not profile_user:
        flash('User not found!', category='error')
        return redirect(url_for('views.home'))

    # Si el usuario actual NO es administrador y no es el mismo que el perfil seleccionado
    if not current_user.is_admin and current_user.id != profile_user.id:
        flash('Access denied. You are not authorized to view this profile.', category='error')
        return redirect(url_for('views.home'))

    # Si el usuario actual NO es administrador pero es el mismo que el perfil seleccionado
    if not current_user.is_admin and current_user.id == profile_user.id:
        return render_template("profile.html", user=current_user, profile_user=profile_user)

    # Si el usuario actual es administrador, muestra el perfil del usuario seleccionado
    return render_template("profile.html", user=current_user, profile_user=profile_user)





@views.route('/add-note/<int:user_id>', methods=['POST'])
@login_required
def add_note(user_id):
    user = User.query.get(user_id)
    if not user:
        flash('User not found!', category='error')
        return redirect(url_for('views.home'))

    if current_user.is_admin or current_user.id == user.id:
        note_text = request.form.get('note')
        if not note_text:
            flash('Note cannot be empty!', category='error')
        else:
            admin_name = None
            if current_user.is_admin:
                admin_name = current_user.first_name  # Usamos 'first_name' como nombre del admin

            new_note = Note(data=note_text, user_id=user_id)
            db.session.add(new_note)
            db.session.commit()
            flash('Note added successfully!', category='success')
    else:
        flash('Access denied. You are not authorized to add notes for this user.', category='error')

    return redirect(url_for('views.user_profile', user_id=user_id))

website/templates/admin_users.html
{% extends "base.html" %} {% block content %}
<!DOCTYPE html>
<html>
  <head>
    <title>User Management</title>
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />
    <style>
      .card-body {
        display: flex;
        justify-content: space-between;
      }
      .user-info {
        flex: 0 0 70%;
      }
      .delete-btn {
        flex: 0 0 20%;
        display: flex;
        align-items: center;
        justify-content: flex-end;
      }
    </style>
  </head>
  <body>
    <div class="container">
      <h1 class="my-4">User Management</h1>

      {% for user in users.items %}
      <div class="card my-3">
        <div class="card-body">
          <div class="user-info">
            <p class="card-text"><strong>Email:</strong> {{ user.email }}</p>
            <p class="card-text">
              <strong>Username:</strong> {{ user.first_name }}
            </p>
            <p class="card-text">
              <strong>Is Admin:</strong> {% if user.is_admin %} Yes {% else %}
              No {% endif %}
            </p>
          </div>
          {% if current_user.is_admin and current_user.id != user.id %}
          <div class="delete-btn">
            <a
              href="{{ url_for('views.user_profile', user_id=user.id) }}"
              class="btn btn-info"
              >View Profile</a
            >
            <form
              action="{{ url_for('views.admin_delete_user', user_id=user.id) }}"
              method="post"
              onsubmit="return confirm('Are you sure you want to delete this user?')"
            >
              <button type="submit" class="btn btn-danger">Delete</button>
            </form>
          </div>
          {% endif %}
        </div>
      </div>
      {% endfor %}

      <div class="d-flex justify-content-center mt-4">
        <nav aria-label="User pagination">
          <ul class="pagination">
            {% if users.has_prev %}
            <li class="page-item">
              <a
                class="page-link"
                href="{{ url_for('views.admin_users', page=users.prev_num) }}"
                >Previous</a
              >
            </li>
            {% endif %} {% for page_num in users.iter_pages() %}
            <li
              class="page-item {% if users.page == page_num %}active{% endif %}"
            >
              <a
                class="page-link"
                href="{{ url_for('views.admin_users', page=page_num) }}"
                >{{ page_num }}</a
              >
            </li>
            {% endfor %} {% if users.has_next %}
            <li class="page-item">
              <a
                class="page-link"
                href="{{ url_for('views.admin_users', page=users.next_num) }}"
                >Next</a
              >
            </li>
            {% endif %}
          </ul>
        </nav>
      </div>

      <a href="{{ url_for('views.home') }}" class="btn btn-primary mt-3"
        >Back to Home</a
      >
    </div>

    {% endblock %}
  </body>
</html>

website/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
      crossorigin="anonymous"
    />

    <title>{% block title %}Home{% endblock %}</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbar"
      >
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbar">
        <div class="navbar-nav">
          {% if user.is_authenticated %}
          <a class="nav-item nav-link" id="home" href="/">Home</a>
          <a class="nav-item nav-link" id="logout" href="/logout">Logout</a>
          {% else %}
          <a class="nav-item nav-link" id="login" href="/login">Login</a>
          <a class="nav-item nav-link" id="signUp" href="/sign-up">Sign Up</a>
          {% endif %} {% if user.is_authenticated and user.is_admin %}
          <a class="nav-item nav-link" id="adminUsers" href="/admin/users"
            >Admin Users</a
          >
          {% endif %}
        </div>
      </div>
    </nav>

    {% with messages = get_flashed_messages(with_categories=true) %} {% if
    messages %} {% for category, message in messages %} {% if category ==
    'error' %}
    <div class="alert alert-danger alter-dismissable fade show" role="alert">
      {{ message }}
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% else %}
    <div class="alert alert-success alter-dismissable fade show" role="alert">
      {{ message }}
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% endif %} {% endfor %} {% endif %} {% endwith %}

    <div class="container">{% block content %} {% endblock %}</div>
    <script
      src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script>

    <script
      type="text/javascript"
      src="{{url_for('static', filename='index.js')}}"
    ></script>
  </body>
</html>

website/templates/edit_note.html
{% extends "base.html" %} {% block content %}
<!DOCTYPE html>
<html>
  <head>
    <title>Edit Note</title>
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />
  </head>
  <body>
    <div class="container mt-4">
      <h1>Edit Note</h1>
      <form method="POST">
        <div class="form-group">
          <label for="new_data">Note:</label>
          <textarea class="form-control" name="new_data" rows="6" cols="50">
{{ note.data }}</textarea
          >
        </div>
        <div class="form-group">
          <button type="submit" class="btn btn-primary">Update Note</button>
          <a href="{{ url_for('views.home') }}" class="btn btn-secondary ml-2"
            >Cancel</a
          >
        </div>
      </form>
    </div>
  </body>
</html>
{% endblock %}

website/templates/home.html
{% extends "base.html" %} {% block title %}Home{% endblock %} {% block content
%}
<div class="container">
  <h1 class="text-center">Notes</h1>
  <ul class="list-group">
    {% for note in user_notes %}
    <li
      class="list-group-item d-flex justify-content-between align-items-center"
    >
      <div>
        {% if note.written_by_admin %}
        <span style="font-weight: bold; color: red"
          >Admin Note - Written by {{ note.admin_name }}</span
        ><br />
        {% endif %}
        <div>{{ note.data }}</div>
      </div>
      <div class="button-group">
        <button
          type="button"
          class="btn btn-danger mr-2"
          onClick="confirmDelete('{{ note.id }}')"
        >
          Delete
        </button>
        <a
          href="{{ url_for('views.edit_note', note_id=note.id) }}"
          class="btn btn-primary"
          >Edit</a
        >
      </div>
    </li>
    {% endfor %}
  </ul>
</div>

<div class="container mt-4">
  <form method="POST">
    <textarea name="note" id="note" class="form-control mb-3"></textarea>
    <div class="text-center">
      <button type="submit" class="btn btn-primary">Add Note</button>
    </div>
  </form>
</div>

<script>
  function confirmDelete(noteId) {
    if (confirm("Are you sure you want to delete this note?")) {
      window.location.href = "/delete-note/" + noteId;
    }
  }
</script>

{% if user_notes.has_prev or user_notes.has_next %}
<div class="d-flex justify-content-center mt-4">
  <nav aria-label="User pagination">
    <ul class="pagination">
      {% if user_notes.has_prev %}
      <li class="page-item">
        <a
          class="page-link"
          href="{{ url_for('views.home', page=user_notes.prev_num) }}"
          >Previous</a
        >
      </li>
      {% endif %} {% for page_num in user_notes.iter_pages() %}
      <li
        class="page-item {% if user_notes.page == page_num %}active{% endif %}"
      >
        <a class="page-link" href="{{ url_for('views.home', page=page_num) }}"
          >{{ page_num }}</a
        >
      </li>
      {% endfor %} {% if user_notes.has_next %}
      <li class="page-item">
        <a
          class="page-link"
          href="{{ url_for('views.home', page=user_notes.next_num) }}"
          >Next</a
        >
      </li>
      {% endif %}
    </ul>
  </nav>
</div>
{% endif %} {% endblock %}

website/templates/login.html
{% extends "base.html" %} {% block title %}Login{% endblock %} {% block content
    %}
    <form method="POST">
      <h3 align="center">Login</h3>
      <div class="form-group">
        <label for="email">Email Address</label>
        <input
          type="email"
          class="form-control"
          id="email"
          name="email"
          placeholder="Enter email"
        />
      </div>
      <div class="form-group">
        <label for="password">Password</label>
        <input
          type="password"
          class="form-control"
          id="password"
          name="password"
          placeholder="Enter password"
        />
      </div>
      <br />
      <button type="submit" class="btn btn-primary">Login</button>
    </form>
    {% endblock %}

website/templates/profile.html
{% extends "base.html" %} {% block content %}
<!DOCTYPE html>
<html>
  <head>
    <title>User Profile</title>
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />
    <style>
      .card-body {
        display: flex;
        justify-content: space-between;
      }

      .user-info {
        flex: 0 0 70%;
      }

      .profile-btn {
        flex: 0 0 20%;
        display: flex;
        align-items: center;
        justify-content: flex-end;
      }

      .notes-container {
        margin-top: 20px;
      }

      .notes-container .list-group-item {
        display: flex;
        justify-content: space-between;
        align-items: center;
      }

      .notes-container .list-group-item .delete-note {
        display: none;
      }
    </style>
  </head>

  <body>
    <div class="container mt-4">
      <h1>User Profile</h1>
      <div class="card">
        <div class="card-header">User Information</div>
        <div class="card-body">
          <h5 class="card-title">Email: {{ profile_user.email }}</h5>
          <p class="card-text">First Name: {{ profile_user.first_name }}</p>
          <p class="card-text">
            Admin Status: {% if profile_user.is_admin %} Yes {% else %} No {%
            endif %}
          </p>
        </div>
      </div>

      {% if current_user.is_admin or current_user.id == profile_user.id %}
      <!-- Sección para admin o el propio usuario -->
      <h3 class="mt-4">Actions for Admin</h3>
      <!-- Agrega aquí cualquier contenido específico para admin o el propio usuario -->
      <div class="profile-btn">
        <form
          action="{{ url_for('views.add_note', user_id=profile_user.id) }}"
          method="post"
        >
          <textarea
            name="note"
            id="note"
            class="form-control mb-3"
            placeholder="Write a note"
          ></textarea>
          <button type="submit" class="btn btn-primary">Add Note</button>
        </form>
      </div>
      {% endif %}

      <div class="notes-container">
        <h3 class="mt-4">User's Notes</h3>
        <ul class="list-group list-group-flush" id="notes">
          {% for note in profile_user.notes %}
          <li class="list-group-item">
            <span>{{ note.data }}</span>
            {% if current_user.is_admin %}
            <button class="btn btn-danger delete-note">Delete</button>
            {% endif %}
          </li>
          {% endfor %}
        </ul>
      </div>
    </div>
  </body>
</html>
{% endblock %}

website/templates/sign_up.html
{% extends "base.html" %} {% block title %}Sign Up{% endblock %} {% block
content %}
<form method="POST" action="{{ url_for('auth.sign_up') }}">
  <h3 align="center">Sign Up</h3>
  <div class="form-group">
    <label for="email">Email Address</label>
    <input
      type="email"
      class="form-control"
      id="email"
      name="email"
      placeholder="Enter email"
    />
  </div>
  <div class="form-group">
    <label for="firstName">First Name</label>
    <input
      type="text"
      class="form-control"
      id="firstName"
      name="firstName"
      placeholder="Enter first name"
    />
  </div>
  <div class="form-group">
    <label for="password1">Password</label>
    <input
      type="password"
      class="form-control"
      id="password1"
      name="password1"
      placeholder="Enter password"
    />
  </div>
  <div class="form-group">
    <label for="password2">Password (Confirm)</label>
    <input
      type="password"
      class="form-control"
      id="password2"
      name="password2"
      placeholder="Confirm password"
    />
  </div>
  <div class="form-group">
    <label for="isAdmin">Are you an administrator?</label>
    <select class="form-control" id="isAdmin" name="isAdmin">
      <option value="0">No</option>
      <option value="1">Yes</option>
    </select>
  </div>
  <br />
  <button type="submit" class="btn btn-primary">Submit</button>
</form>
{% endblock %}